apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
    - protocol: TCP
      port: 80        # The port exposed outside
      targetPort: 80  # The port inside your pod
      # nodePort: 30007  # Optional if you want a specific NodePort
